name:                video-to-audio
version:             0.1.0.0
github:              "githubuser/video-to-audio"
license:             BSD3
author:              "Choon Ken Ding"
maintainer:          "example@example.com"
copyright:           "2020 Choon Ken Ding"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/video-to-audio#readme>

dependencies:
- base >= 4.7 && < 5
- turtle
- text
- foldl
- containers

library:
  source-dirs: src

executables:
  convert:
    source-dirs:         driver/convert
    main:                Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - video-to-audio
  stitch:
    source-dirs:         driver/stitch
    main:                Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - video-to-audio

tests:
  video-to-audio-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - video-to-audio
