version: "3.8"
services:
  dev:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.build
    command: stack ghci
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - ..:/opt/ken-ding/apps/sparrow


